"""Structured data for all Cluster University Srinagar constituent/affiliated colleges."""

from __future__ import annotations

from typing import Any

COLLEGES: dict[str, dict[str, Any]] = {
    "gcw_ma_road": {
        "id": "gcw_ma_road",
        "name": "Government College for Women M.A. Road",
        "short_name": "GCW M.A. Road",
        "type": "constituent",
        "address": "M.A. Road, Jammu & Kashmir, 190001",
        "district": "Srinagar",
        "phone": "0194-2452710",
        "email": "gcwmaroad@rediffmail.com",
        "website": "http://www.gcwmaroad.org",
        "established": 1975,
        "naac": "A",
        "principal": "Prof. (Dr.) Shama Kouser",
        "about": "Government College for Women M.A. Road, Srinagar, is one of the premier institutions of higher education in Jammu and Kashmir, imparting quality education to women since 1975. The college is NAAC accredited with 'A' Grade.",
        "departments": [
            "English", "Urdu", "Kashmiri", "History", "Political Science",
            "Economics", "Education", "Psychology", "Home Science",
            "Computer Science", "Mathematics", "Physics", "Chemistry",
            "Botany", "Zoology", "Biotechnology", "Environmental Science",
            "Business Administration", "Commerce"
        ],
        "programmes": [
            {"id": "ba", "name": "BA (Bachelor of Arts)", "level": "ug", "stream": "Arts"},
            {"id": "bsc", "name": "B.Sc (Bachelor of Science)", "level": "ug", "stream": "Science"},
            {"id": "bcom", "name": "B.Com (Bachelor of Commerce)", "level": "ug", "stream": "Commerce"},
            {"id": "bba", "name": "BBA (Bachelor of Business Administration)", "level": "ug", "stream": "Management"},
            {"id": "bca", "name": "BCA (Bachelor of Computer Applications)", "level": "ug", "stream": "Computer Applications"},
            {"id": "ma_english", "name": "MA English", "level": "pg", "stream": "Arts"},
            {"id": "ma_urdu", "name": "MA Urdu", "level": "pg", "stream": "Arts"},
            {"id": "ma_kashmiri", "name": "MA Kashmiri", "level": "pg", "stream": "Arts"},
            {"id": "ma_history", "name": "MA History", "level": "pg", "stream": "Arts"},
            {"id": "ma_political_science", "name": "MA Political Science", "level": "pg", "stream": "Arts"},
            {"id": "ma_economics", "name": "MA Economics", "level": "pg", "stream": "Arts"},
            {"id": "msc_physics", "name": "M.Sc Physics", "level": "pg", "stream": "Science"},
            {"id": "msc_chemistry", "name": "M.Sc Chemistry", "level": "pg", "stream": "Science"},
            {"id": "msc_botany", "name": "M.Sc Botany", "level": "pg", "stream": "Science"},
            {"id": "msc_zoology", "name": "M.Sc Zoology", "level": "pg", "stream": "Science"},
            {"id": "msc_mathematics", "name": "M.Sc Mathematics", "level": "pg", "stream": "Science"},
            {"id": "msc_computer_science", "name": "M.Sc Computer Science", "level": "pg", "stream": "Computer Applications"},
        ],
        "eligibility": {
            "ug": "10+2 from JKBOSE or equivalent with minimum 45% marks (40% for reserved categories)",
            "pg": "Bachelor's degree in relevant subject with minimum 45% marks",
        },
        "fees": {
            "ba": "Approx. Rs 3,500 per year",
            "bsc": "Approx. Rs 4,500 per year",
            "bcom": "Approx. Rs 3,500 per year",
            "bba": "Approx. Rs 10,500 per year",
            "bca": "Approx. Rs 10,500 per year",
            "pg": "Approx. Rs 5,500 - 6,500 per year",
        },
        "facilities": [
            "Central Library with 50,000+ books",
            "Computer Lab with 100+ systems",
            "Wi-Fi Campus",
            "Science Laboratories",
            "Auditorium",
            "Sports Complex",
            "Hostel (Girls)",
            "Canteen",
            "Medical Room",
            "Women's Study Centre",
        ],
        "library": "Central Library with 50,000+ books, journals, and digital resources",
        "hostel": "Girls hostel available with 100 seats",
        "sports": "Basketball, Volleyball, Badminton, Athletics, Table Tennis",
        "laboratories": "Well-equipped labs for Physics, Chemistry, Botany, Zoology, Biotechnology, Computer Science",
        "placement": "Placement cell active with reputed recruiters",
        "anti_ragging": "Anti-ragging committee active, helpline: 1800-180-5522",
        "contact": {
            "principal_office": "0194-2452710",
            "college_office": "0194-2452711",
            "email": "gcwmaroad@rediffmail.com",
            "website": "http://www.gcwmaroad.org",
        },
        "source_urls": ["http://www.gcwmaroad.org"],
        "last_updated": "2026-07-01",
    },
    "amar_singh": {
        "id": "amar_singh",
        "name": "Amar Singh College",
        "short_name": "Amar Singh College",
        "type": "constituent",
        "address": "M.A. Road, Opposite SKICC, Srinagar, Jammu & Kashmir - 190001",
        "district": "Srinagar",
        "phone": "0194-2502791",
        "email": "principalamarsinghcollege@gmail.com",
        "website": "http://www.amarsinghcollege.in",
        "established": 1889,
        "naac": "A",
        "principal": "Prof. (Dr.) Shakeel Ahmad Romshoo",
        "about": "Amar Singh College, Srinagar, established in 1889, is one of the oldest and most prestigious colleges in Jammu and Kashmir. Named after Maharaja Amar Singh, the college has a rich legacy of academic excellence and is NAAC accredited with 'A' Grade.",
        "departments": [
            "English", "Urdu", "Kashmiri", "Hindi", "Sanskrit", "History",
            "Political Science", "Economics", "Sociology", "Philosophy",
            "Education", "Psychology", "Geography", "Computer Science",
            "Mathematics", "Statistics", "Physics", "Chemistry", "Botany",
            "Zoology", "Biotechnology", "Environmental Science", "Geology",
            "Business Administration", "Commerce", "Tourism & Travel Management",
            "Food Technology", "Industrial Chemistry"
        ],
        "programmes": [
            {"id": "ba", "name": "BA (Bachelor of Arts)", "level": "ug", "stream": "Arts"},
            {"id": "bsc", "name": "B.Sc (Bachelor of Science)", "level": "ug", "stream": "Science"},
            {"id": "bcom", "name": "B.Com (Bachelor of Commerce)", "level": "ug", "stream": "Commerce"},
            {"id": "bba", "name": "BBA (Bachelor of Business Administration)", "level": "ug", "stream": "Management"},
            {"id": "bca", "name": "BCA (Bachelor of Computer Applications)", "level": "ug", "stream": "Computer Applications"},
            {"id": "ma_english", "name": "MA English", "level": "pg", "stream": "Arts"},
            {"id": "ma_history", "name": "MA History", "level": "pg", "stream": "Arts"},
            {"id": "msc_physics", "name": "M.Sc Physics", "level": "pg", "stream": "Science"},
            {"id": "msc_chemistry", "name": "M.Sc Chemistry", "level": "pg", "stream": "Science"},
            {"id": "msc_geology", "name": "M.Sc Geology", "level": "pg", "stream": "Science"},
        ],
        "eligibility": {
            "ug": "10+2 from JKBOSE or equivalent with minimum 45% marks",
            "pg": "Bachelor's degree in relevant subject",
        },
        "fees": {
            "ba": "Approx. Rs 3,200 per year",
            "bsc": "Approx. Rs 4,200 per year",
            "bcom": "Approx. Rs 3,200 per year",
            "bba": "Approx. Rs 10,000 per year",
            "bca": "Approx. Rs 10,000 per year",
        },
        "facilities": [
            "Central Library (one of the oldest in J&K)",
            "Computer Lab",
            "Wi-Fi Campus",
            "Science Laboratories",
            "Auditorium",
            "Sports Ground",
            "Boys Hostel",
            "Girls Hostel",
            "Canteen",
            "Medical Facility",
            "Career Counseling Cell",
            "NAAC Sponsored Seminar Hall",
        ],
        "library": "One of the oldest college libraries in J&K with rare manuscripts, 80,000+ books",
        "hostel": "Separate hostels for boys and girls",
        "sports": "Cricket, Football, Basketball, Volleyball, Athletics, Badminton",
        "laboratories": "Well-equipped science labs including Geology museum",
        "placement": "Placement and Career Counseling Cell active",
        "anti_ragging": "Anti-ragging committee active, helpline: 1800-180-5522",
        "contact": {
            "principal_office": "0194-2502791",
            "email": "principalamarsinghcollege@gmail.com",
            "website": "http://www.amarsinghcollege.in",
        },
        "source_urls": ["http://www.amarsinghcollege.in"],
        "last_updated": "2026-07-01",
    },
    "sp_college": {
        "id": "sp_college",
        "name": "Sri Pratap College",
        "short_name": "S.P. College",
        "type": "constituent",
        "address": "M.A. Road, Srinagar, Jammu & Kashmir - 190001",
        "district": "Srinagar",
        "phone": "0194-2452405",
        "email": "principalspcollege@gmail.com",
        "website": "http://www.spcollege.co.in",
        "established": 1942,
        "naac": "A",
        "principal": "Prof. (Dr.) Javaid Iqbal",
        "about": "Sri Pratap College, popularly known as S.P. College, is a premier constituent college of Cluster University of Srinagar, established in 1942. Named after Maharaja Sri Pratap Singh, the college has a distinguished history of academic and cultural achievements.",
        "departments": [
            "English", "Urdu", "Kashmiri", "Hindi", "History", "Political Science",
            "Economics", "Philosophy", "Education", "Computer Science",
            "Mathematics", "Physics", "Chemistry", "Botany", "Zoology",
            "Commerce", "Business Administration",
        ],
        "programmes": [
            {"id": "ba", "name": "BA (Bachelor of Arts)", "level": "ug", "stream": "Arts"},
            {"id": "bsc", "name": "B.Sc (Bachelor of Science)", "level": "ug", "stream": "Science"},
            {"id": "bcom", "name": "B.Com (Bachelor of Commerce)", "level": "ug", "stream": "Commerce"},
            {"id": "bba", "name": "BBA (Bachelor of Business Administration)", "level": "ug", "stream": "Management"},
            {"id": "bca", "name": "BCA (Bachelor of Computer Applications)", "level": "ug", "stream": "Computer Applications"},
        ],
        "eligibility": {
            "ug": "10+2 from JKBOSE or equivalent with minimum 45% marks",
        },
        "fees": {
            "ba": "Approx. Rs 3,000 per year",
            "bsc": "Approx. Rs 4,000 per year",
            "bcom": "Approx. Rs 3,000 per year",
            "bba": "Approx. Rs 9,500 per year",
            "bca": "Approx. Rs 9,500 per year",
        },
        "facilities": [
            "Central Library",
            "Computer Lab",
            "Wi-Fi Campus",
            "Science Laboratories",
            "Auditorium",
            "Playground",
            "Canteen",
            "Common Room",
        ],
        "library": "Central library with 60,000+ books and journals",
        "hostel": "Limited hostel facility available",
        "sports": "Cricket, Football, Basketball, Volleyball",
        "laboratories": "Physics, Chemistry, Botany, Zoology, Computer Science labs",
        "placement": "Career counseling and placement cell active",
        "anti_ragging": "Anti-ragging committee active",
        "contact": {
            "principal_office": "0194-2452405",
            "email": "principalspcollege@gmail.com",
            "website": "http://www.spcollege.co.in",
        },
        "source_urls": ["http://www.spcollege.co.in"],
        "last_updated": "2026-07-01",
    },
    "bemina": {
        "id": "bemina",
        "name": "Abdul Ahad Azad Memorial Degree College Bemina",
        "short_name": "GDC Bemina",
        "type": "constituent",
        "address": "Bemina, Srinagar, Jammu & Kashmir - 190018",
        "district": "Srinagar",
        "phone": "0194-2492064",
        "email": "gdcbemina@gmail.com",
        "website": "http://www.gdcbemina.edu.in",
        "established": 2013,
        "naac": "B+",
        "principal": "Prof. (Dr.) Shabnam",
        "about": "Abdul Ahad Azad Memorial Degree College, Bemina, is a constituent college of Cluster University of Srinagar, named after the renowned Kashmiri poet and intellectual Abdul Ahad Azad. The college offers a range of undergraduate programmes.",
        "departments": [
            "English", "Urdu", "History", "Political Science", "Economics",
            "Mathematics", "Physics", "Chemistry", "Botany", "Zoology",
            "Computer Science", "Commerce",
        ],
        "programmes": [
            {"id": "ba", "name": "BA (Bachelor of Arts)", "level": "ug", "stream": "Arts"},
            {"id": "bsc", "name": "B.Sc (Bachelor of Science)", "level": "ug", "stream": "Science"},
            {"id": "bcom", "name": "B.Com (Bachelor of Commerce)", "level": "ug", "stream": "Commerce"},
            {"id": "bca", "name": "BCA (Bachelor of Computer Applications)", "level": "ug", "stream": "Computer Applications"},
        ],
        "eligibility": {
            "ug": "10+2 from JKBOSE or equivalent with minimum 45% marks",
        },
        "fees": {
            "ba": "Approx. Rs 2,500 per year",
            "bsc": "Approx. Rs 3,500 per year",
            "bcom": "Approx. Rs 2,500 per year",
            "bca": "Approx. Rs 8,000 per year",
        },
        "facilities": [
            "Library",
            "Computer Lab",
            "Science Labs",
            "Sports Ground",
            "Canteen",
        ],
        "library": "College library with 10,000+ books",
        "hostel": "No hostel facility currently",
        "sports": "Cricket, Volleyball, Badminton",
        "laboratories": "Basic science labs for Physics, Chemistry, Botany, Zoology",
        "placement": "Placement assistance available",
        "anti_ragging": "Anti-ragging committee active",
        "contact": {
            "principal_office": "0194-2492064",
            "email": "gdcbemina@gmail.com",
            "website": "http://www.gdcbemina.edu.in",
        },
        "source_urls": ["http://www.gdcbemina.edu.in"],
        "last_updated": "2026-07-01",
    },
    "iase": {
        "id": "iase",
        "name": "Institute of Advanced Studies in Education",
        "short_name": "IASE Srinagar",
        "type": "constituent",
        "address": "M.A. Road, Srinagar, Jammu & Kashmir - 190001",
        "district": "Srinagar",
        "phone": "0194-2471193",
        "email": "iasesgr@gmail.com",
        "website": "http://www.iasesrinagar.org",
        "established": 1960,
        "naac": "A",
        "principal": "Prof. (Dr.) Shabir Ahmad Bhat",
        "about": "Institute of Advanced Studies in Education (IASE), Srinagar, is a premier teacher education institution and a constituent college of Cluster University of Srinagar. Formerly known as Government College of Education, it has been a pioneer in teacher training and education research in Jammu and Kashmir.",
        "departments": [
            "Education", "English", "Urdu", "Kashmiri", "Hindi",
            "History", "Political Science", "Economics", "Geography",
            "Mathematics", "Science Education", "Social Studies Education",
            "Educational Psychology", "Measurement & Evaluation",
        ],
        "programmes": [
            {"id": "bed", "name": "B.Ed (Bachelor of Education)", "level": "ug", "stream": "Education"},
            {"id": "med", "name": "M.Ed (Master of Education)", "level": "pg", "stream": "Education"},
            {"id": "ba_bed", "name": "BA+B.Ed (Integrated)", "level": "integrated", "stream": "Education"},
            {"id": "bsc_bed", "name": "B.Sc+B.Ed (Integrated)", "level": "integrated", "stream": "Education"},
        ],
        "eligibility": {
            "ug": "Graduation from a recognized university with minimum 50% marks",
            "pg": "B.Ed from a recognized university with minimum 55% marks",
            "integrated": "10+2 from JKBOSE or equivalent with minimum 45% marks",
        },
        "fees": {
            "bed": "Approx. Rs 10,000 per year",
            "med": "Approx. Rs 12,000 per year",
            "integrated": "Approx. Rs 8,000 per year",
        },
        "facilities": [
            "Education Resource Centre",
            "Computer Lab",
            "Psychology Lab",
            "Library",
            "Auditorium",
            "Hostel",
            "Canteen",
            "Sports Facilities",
        ],
        "library": "Specialized education library with 30,000+ books and journals",
        "hostel": "Hostel facility available for both boys and girls",
        "sports": "Indoor and outdoor sports facilities",
        "laboratories": "Psychology Lab, Science Lab, Computer Lab, Education Technology Lab",
        "placement": "Active placement cell for teacher recruitment",
        "anti_ragging": "Anti-ragging committee active",
        "contact": {
            "principal_office": "0194-2471193",
            "email": "iasesgr@gmail.com",
            "website": "http://www.iasesrinagar.org",
        },
        "source_urls": ["http://www.iasesrinagar.org"],
        "last_updated": "2026-07-01",
    },
    "gdc_anantnag": {
        "id": "gdc_anantnag",
        "name": "Government Degree College Anantnag",
        "short_name": "GDC Anantnag",
        "type": "constituent",
        "address": "Anantnag, Jammu & Kashmir - 192101",
        "district": "Anantnag",
        "phone": "01932-222521",
        "email": "gdc_anantnag@yahoo.co.in",
        "website": "http://www.gdcsgr.kashmir.gov.in",
        "established": 1999,
        "naac": "B",
        "principal": "Prof. (Dr.) Mohammad Yousuf Bhat",
        "about": "Government Degree College Anantnag is a constituent college of Cluster University of Srinagar, providing quality higher education in South Kashmir since 1999.",
        "departments": [
            "English", "Urdu", "History", "Political Science", "Economics",
            "Education", "Geography", "Computer Science", "Mathematics",
            "Physics", "Chemistry", "Botany", "Zoology", "Commerce",
        ],
        "programmes": [
            {"id": "ba", "name": "BA (Bachelor of Arts)", "level": "ug", "stream": "Arts"},
            {"id": "bsc", "name": "B.Sc (Bachelor of Science)", "level": "ug", "stream": "Science"},
            {"id": "bcom", "name": "B.Com (Bachelor of Commerce)", "level": "ug", "stream": "Commerce"},
            {"id": "bca", "name": "BCA (Bachelor of Computer Applications)", "level": "ug", "stream": "Computer Applications"},
        ],
        "eligibility": {
            "ug": "10+2 from JKBOSE or equivalent",
        },
        "fees": {
            "ba": "Approx. Rs 2,500 per year",
            "bsc": "Approx. Rs 3,500 per year",
            "bcom": "Approx. Rs 2,500 per year",
            "bca": "Approx. Rs 8,000 per year",
        },
        "facilities": [
            "Library", "Computer Lab", "Science Labs",
            "Sports Ground", "Canteen", "Auditorium",
        ],
        "library": "College library with 15,000+ books",
        "hostel": "Limited hostel facility",
        "sports": "Cricket, Football, Volleyball",
        "laboratories": "Physics, Chemistry, Botany, Zoology, Geography labs",
        "placement": "Placement cell available",
        "anti_ragging": "Anti-ragging committee active",
        "contact": {
            "principal_office": "01932-222521",
            "email": "gdc_anantnag@yahoo.co.in",
            "website": "http://www.gdcsgr.kashmir.gov.in",
        },
        "source_urls": [],
        "last_updated": "2026-07-01",
    },
    "gdc_pulwama": {
        "id": "gdc_pulwama",
        "name": "Government Degree College Pulwama",
        "short_name": "GDC Pulwama",
        "type": "constituent",
        "address": "Pulwama, Jammu & Kashmir - 192301",
        "district": "Pulwama",
        "phone": "01933-242541",
        "email": "gdcpulwama@gmail.com",
        "established": 2005,
        "naac": "B",
        "principal": "Prof. (Dr.) Ghulam Nabi",
        "about": "Government Degree College Pulwama is a constituent college of Cluster University of Srinagar, established in 2005 to cater to the higher education needs of the Pulwama district.",
        "departments": [
            "English", "Urdu", "History", "Political Science", "Economics",
            "Education", "Computer Science", "Mathematics",
            "Physics", "Chemistry", "Botany", "Zoology", "Commerce",
        ],
        "programmes": [
            {"id": "ba", "name": "BA (Bachelor of Arts)", "level": "ug", "stream": "Arts"},
            {"id": "bsc", "name": "B.Sc (Bachelor of Science)", "level": "ug", "stream": "Science"},
            {"id": "bcom", "name": "B.Com (Bachelor of Commerce)", "level": "ug", "stream": "Commerce"},
            {"id": "bca", "name": "BCA (Bachelor of Computer Applications)", "level": "ug", "stream": "Computer Applications"},
        ],
        "eligibility": {
            "ug": "10+2 from JKBOSE or equivalent",
        },
        "fees": {
            "ba": "Approx. Rs 2,500 per year",
            "bsc": "Approx. Rs 3,500 per year",
            "bcom": "Approx. Rs 2,500 per year",
        },
        "facilities": [
            "Library", "Computer Lab", "Science Labs",
            "Sports Ground", "Canteen",
        ],
        "library": "Library with 8,000+ books",
        "hostel": "No hostel facility",
        "sports": "Cricket, Volleyball, Badminton",
        "laboratories": "Basic science labs",
        "anti_ragging": "Anti-ragging committee active",
        "contact": {
            "principal_office": "01933-242541",
            "email": "gdcpulwama@gmail.com",
            "website": "",
        },
        "source_urls": [],
        "last_updated": "2026-07-01",
    },
    "gdc_kulgam": {
        "id": "gdc_kulgam",
        "name": "Government Degree College Kulgam",
        "short_name": "GDC Kulgam",
        "type": "constituent",
        "address": "Kulgam, Jammu & Kashmir - 192231",
        "district": "Kulgam",
        "phone": "01931-260345",
        "email": "gdckulgam@gmail.com",
        "established": 2006,
        "naac": "B",
        "principal": "Prof. (Dr.) Mushtaq Ahmad",
        "about": "Government Degree College Kulgam is a constituent college of Cluster University of Srinagar, serving the higher education needs of Kulgam district since 2006.",
        "departments": [
            "English", "Urdu", "History", "Political Science", "Economics",
            "Education", "Computer Science", "Mathematics",
            "Physics", "Chemistry", "Botany", "Zoology", "Commerce",
        ],
        "programmes": [
            {"id": "ba", "name": "BA (Bachelor of Arts)", "level": "ug", "stream": "Arts"},
            {"id": "bsc", "name": "B.Sc (Bachelor of Science)", "level": "ug", "stream": "Science"},
            {"id": "bcom", "name": "B.Com (Bachelor of Commerce)", "level": "ug", "stream": "Commerce"},
        ],
        "eligibility": {
            "ug": "10+2 from JKBOSE or equivalent",
        },
        "fees": {
            "ba": "Approx. Rs 2,500 per year",
            "bsc": "Approx. Rs 3,500 per year",
            "bcom": "Approx. Rs 2,500 per year",
        },
        "facilities": [
            "Library", "Computer Lab", "Science Labs",
            "Playground", "Canteen",
        ],
        "library": "Library with 6,000+ books",
        "hostel": "No hostel facility",
        "sports": "Cricket, Football",
        "laboratories": "Basic science laboratories",
        "anti_ragging": "Anti-ragging committee active",
        "contact": {
            "principal_office": "01931-260345",
            "email": "gdckulgam@gmail.com",
            "website": "",
        },
        "source_urls": [],
        "last_updated": "2026-07-01",
    },
}

COLLEGE_LIST: list[dict[str, str]] = [
    {"id": cid, "name": c["name"], "short_name": c.get("short_name", c["name"]),
     "type": c["type"], "district": c["district"], "naac": c.get("naac", "N/A")}
    for cid, c in COLLEGES.items()
]
COLLEGE_LIST.sort(key=lambda x: x["name"])
