"""
backend/app/orchestrator/intent_kb.py

Intent knowledge base — canonical intents with hundreds of paraphrases
for semantic matching. Each intent has 15–50+ natural-language variations
covering different phrasings, formality levels, and question styles.
"""

from __future__ import annotations

# Each intent maps to a canonical category id used by get_broad_response() / planner.
# The existing navigation categories from intent_router.py are preserved:
#   admissions, ug, pg, phd, integrated, dyd, courses, fee, results,
#   datesheet, syllabus, scholarships, previous_papers, notices, downloads,
#   hostel, examination, departments, colleges, contact
#
# Additional semantic-only intents:
#   eligibility, authorities

INTENT_PARAPHRASES: dict[str, list[str]] = {

    # =========================================================================
    # Courses — what programmes / courses are offered
    # =========================================================================
    "courses": [
        "courses",
        "course",
        "what courses are offered",
        "what courses do you offer",
        "what programmes are available",
        "available courses",
        "available programmes",
        "list of courses",
        "list of programmes",
        "programmes offered",
        "programs offered",
        "courses offered",
        "course list",
        "programme list",
        "what can i study",
        "what can i study here",
        "what can i study at this university",
        "what subjects are available",
        "what subjects do you offer",
        "academic programmes",
        "academic courses",
        "what programmes do you have",
        "what programmes are offered",
        "which programmes are available",
        "which courses are available",
        "tell me about courses",
        "tell me about your programmes",
        "tell me about available courses",
        "i want to see courses",
        "show me courses",
        "show me programmes",
        "show me available courses",
        "degrees offered",
        "what degrees do you offer",
        "what degrees are available",
        "degree programmes",
        "list all programmes",
        "list all courses",
        "what are the programmes",
        "what are the courses",
        "course offerings",
        "programme offerings",
        "which programmes do you offer",
        "what are the academic programmes",
        "i want to know about courses",
        "i want to know about programmes",
        "can you tell me about courses",
        "can you tell me about programmes",
        "study options",
        "what study options are available",
        "study programmes",
        "educational programmes",
        "fields of study",
        "areas of study",
        "what fields can i study",
        "available fields of study",
        "what can i major in",
        "what majors are available",
        "what specialisations do you offer",
        "what specializations do you offer",
        "list of academic programmes",
        "course catalogue",
        "programme catalogue",
        "academic offerings",
        "curriculum offerings",
        "what are the different programmes",
        "what are the different courses",
        "what programmes do you run",
        "all courses",
        "all programmes",
        "full list of courses",
        "full list of programmes",
        "i want to browse courses",
        "i want to browse programmes",
        "course directory",
        "programme directory",
        "what can i enrol in",
        "what can i enroll in",
        "what subjects can i take",
    ],

    # =========================================================================
    # Admissions — admission process, how to apply
    # =========================================================================
    "admissions": [
        "admissions",
        "admission",
        "admission process",
        "how to apply",
        "how do i apply",
        "how can i apply",
        "how to get admission",
        "how do i get admission",
        "how can i get admission",
        "admission procedure",
        "admission details",
        "admission info",
        "admission information",
        "apply for admission",
        "applying to the university",
        "application process",
        "application procedure",
        "how to apply for admission",
        "how do i apply for admission",
        "i want to apply",
        "i want to take admission",
        "i want to get admitted",
        "tell me about admissions",
        "tell me about the admission process",
        "what is the admission process",
        "what are the admission requirements",
        "admission requirements",
        "admission criteria",
        "how to enrol",
        "how to enroll",
        "enrolment process",
        "enrollment process",
        "how do i enrol",
        "how do i enroll",
        "how can i enrol",
        "how can i enroll",
        "admission application",
        "online admission",
        "admission portal",
        "apply online",
        "admission form",
        "admission 2026",
        "admission 2025",
        "admission this year",
        "admission for next session",
        "how to take admission",
        "steps for admission",
        "admission steps",
        "admission guidelines",
        "admission guide",
        "admission related",
        "about admission",
        "i want admission",
        "i need admission",
        "seeking admission",
        "admission enquiry",
        "admission inquiry",
        "admission help",
        "admission assistance",
        "process of admission",
        "how to get admitted",
        "how can i get admitted",
        "what do i need for admission",
        "documents required for admission",
        "admission documents",
        "admission instructions",
        "how to register for admission",
        "registration for admission",
        "admission registration",
        "when does admission start",
        "when are admissions open",
        "admission dates",
        "admission schedule",
        "admission timeline",
        "how to fill admission form",
    ],

    # =========================================================================
    # Fee Structure — costs, tuition, fees
    # =========================================================================
    "fee": [
        "fee",
        "fees",
        "fee structure",
        "fee details",
        "fee information",
        "fee info",
        "what are the fees",
        "how much are the fees",
        "how much does it cost",
        "what is the fee",
        "what is the fee structure",
        "what are the fee details",
        "tuition fee",
        "tuition fees",
        "course fee",
        "course fees",
        "programme fee",
        "programme fees",
        "academic fee",
        "academic fees",
        "semester fee",
        "semester fees",
        "annual fee",
        "annual fees",
        "yearly fee",
        "yearly fees",
        "fee for each course",
        "fee for each programme",
        "fee for bca",
        "fee for mba",
        "fee for btech",
        "cost of study",
        "how much do i have to pay",
        "what do i need to pay",
        "payment details",
        "fee payment",
        "how to pay fee",
        "fee payment method",
        "fee payment process",
        "what is the cost",
        "how much will it cost me",
        "total fee",
        "total fees",
        "fee per year",
        "fee per semester",
        "fee structure for courses",
        "fee structure for programmes",
        "fee structure for ug",
        "fee structure for pg",
        "fee structure for phd",
        "what are the charges",
        "how much money do i need",
        "fee break up",
        "fee breakup",
        "fee breakdown",
        "detailed fee structure",
        "fee details for each course",
        "fee details for each programme",
        "how much is tuition",
        "tuition costs",
        "educational expenses",
        "what is the tuition fee",
    ],

    # =========================================================================
    # Eligibility — who can apply, requirements
    # =========================================================================
    "eligibility": [
        "eligibility",
        "eligible",
        "eligibility criteria",
        "eligibility requirements",
        "who can apply",
        "who is eligible",
        "am i eligible",
        "what are the eligibility criteria",
        "what are the eligibility requirements",
        "eligibility conditions",
        "minimum requirements",
        "educational requirements",
        "academic requirements",
        "what qualifications do i need",
        "what are the requirements",
        "requirements for admission",
        "qualification required",
        "qualifications needed",
        "what qualification is required",
        "what qualifications are needed",
        "entry requirements",
        "entry criteria",
        "admission eligibility",
        "eligibility for bca",
        "eligibility for mba",
        "eligibility for btech",
        "eligibility for ug",
        "eligibility for pg",
        "eligibility for phd",
        "what marks do i need",
        "what percentage is required",
        "minimum marks required",
        "minimum percentage required",
        "required percentage",
        "required marks",
        "cut off marks",
        "cutoff marks",
        "what is the cut off",
        "academic eligibility",
        "who can take admission",
        "who can get admission",
        "who is eligible for admission",
        "eligibility conditions for courses",
        "what are the minimum qualifications",
        "eligibility for various programmes",
        "qualifying criteria",
        "basic requirements",
        "eligibility norms",
        "what are the basic requirements",
        "selection criteria",
        "what are the selection criteria",
        "how to be eligible",
    ],

    # =========================================================================
    # Scholarships — financial aid, scholarships
    # =========================================================================
    "scholarships": [
        "scholarships",
        "scholarship",
        "scholarship information",
        "scholarship details",
        "financial aid",
        "financial assistance",
        "what scholarships are available",
        "what scholarships do you offer",
        "scholarship programmes",
        "scholarship programmes",
        "scholarship opportunities",
        "how to apply for scholarship",
        "how can i get scholarship",
        "how do i get scholarship",
        "am i eligible for scholarship",
        "scholarship eligibility",
        "scholarship criteria",
        "what is the scholarship",
        "tell me about scholarships",
        "about scholarships",
        "scholarship for ug students",
        "scholarship for pg students",
        "scholarship for phd students",
        "merit scholarship",
        "merit based scholarship",
        "merit cum means scholarship",
        "means scholarship",
        "government scholarship",
        "nsp scholarship",
        "national scholarship portal",
        "post matric scholarship",
        "ugc scholarship",
        "ugc fellowship",
        "research fellowship",
        "financial support",
        "fee waiver",
        "tuition waiver",
        "education loan",
        "financial help",
        "funding opportunities",
        "how to get financial aid",
        "what financial aid is available",
        "scholarship list",
        "list of scholarships",
        "available scholarships",
        "scholarship schemes",
        "schemes for students",
        "student financial aid",
        "aid for students",
        "is there any scholarship",
        "any scholarship for me",
        "can i get scholarship",
        "scholarship amount",
        "scholarship benefits",
        "how much scholarship",
    ],

    # =========================================================================
    # Datesheets — exam schedule, date sheets
    # =========================================================================
    "datesheet": [
        "datesheet",
        "date sheet",
        "date sheets",
        "date-sheet",
        "exam schedule",
        "examination schedule",
        "exam time table",
        "exam timetable",
        "examination timetable",
        "examination time table",
        "when are the exams",
        "when will exams be held",
        "exam dates",
        "examination dates",
        "exam date",
        "examination date",
        "when is the exam",
        "when is the examination",
        "schedule of exams",
        "schedule of examinations",
        "when do exams start",
        "when do examinations start",
        "exam routine",
        "examination routine",
        "tentative date sheet",
        "final date sheet",
        "semester exam schedule",
        "semester exam dates",
        "ug exam schedule",
        "pg exam schedule",
        "annual exam schedule",
        "exam calendar",
        "academic calendar",
        "important dates exams",
        "exam datesheet",
        "when are my exams",
        "show me the date sheet",
        "i want to see the date sheet",
        "when will the exams be conducted",
        "exam time",
        "exam timing",
        "examination timing",
        "university exam schedule",
        "what is the exam schedule",
        "what is the date sheet",
        "tell me the date sheet",
        "tell me the exam schedule",
        "show exam schedule",
    ],

    # =========================================================================
    # Results — exam results, marks
    # =========================================================================
    "results": [
        "results",
        "result",
        "exam results",
        "examination results",
        "my results",
        "my result",
        "how to check results",
        "how to check result",
        "how do i check my results",
        "how do i check my result",
        "how can i check my results",
        "how can i check my result",
        "where can i see my results",
        "where can i see my result",
        "check results",
        "check result",
        "view results",
        "view result",
        "online results",
        "online result",
        "semester results",
        "semester result",
        "ug results",
        "ug result",
        "pg results",
        "pg result",
        "university results",
        "university result",
        "when will results be announced",
        "when are results announced",
        "result status",
        "result date",
        "result declaration date",
        "when will my result come",
        "when will the results be out",
        "have results been declared",
        "are results out",
        "marks",
        "marksheet",
        "marks card",
        "grade card",
        "grade cards",
        "grades",
        "my marks",
        "my grades",
        "i want to check my result",
        "i want to check my marks",
        "i want to see my result",
        "show me my result",
        "show me my marks",
        "result portal",
        "nep results",
        "btech results",
        "bed results",
        "integrated results",
    ],

    # =========================================================================
    # Examinations — exam process, information about exams
    # =========================================================================
    "examination": [
        "examination",
        "examinations",
        "exam",
        "exams",
        "examination information",
        "exam information",
        "examination details",
        "exam details",
        "examination process",
        "exam process",
        "examination system",
        "examination branch",
        "examination department",
        "controller of examinations",
        "coe",
        "examination cell",
        "examination section",
        "exam related",
        "examination related",
        "about examinations",
        "about exams",
        "tell me about examinations",
        "tell me about exams",
        "examination services",
        "exam services",
        "examination rules",
        "exam rules",
        "examination policy",
        "exam policy",
        "examination guidelines",
        "exam guidelines",
        "examination regulations",
        "exam regulations",
        "examination help",
        "exam help",
        "examination enquiry",
        "exam enquiry",
        "examination inquiry",
        "exam inquiry",
        "model papers",
        "model question papers",
        "previous year question papers",
        "previous year papers",
        "question bank",
        "sample papers",
        "practice papers",
        "exam material",
        "study material",
        "exam preparation",
        "preparation for exams",
        "how to prepare for exams",
        "exam tips",
        "exam advice",
        "exam fee",
        "examination fee",
        "exam fee structure",
        "division improvement",
        "improvement exam",
        "re evaluation",
        "reevaluation",
        "re-evaluation",
        "revaluation",
        "reval",
        "photo copy of answer sheet",
        "photocopy of answer sheet",
        "xerox of answer sheet",
        "xerox copy",
        "answer sheet copy",
    ],

    # =========================================================================
    # Authorities — university offices, departments, staff
    # =========================================================================
    "authorities": [
        "authorities",
        "authority",
        "university authorities",
        "university offices",
        "offices",
        "university staff",
        "faculty members",
        "professors",
        "department heads",
        "hod",
        "head of department",
        "vice chancellor",
        "vc",
        "vice chancellor office",
        "registrar",
        "registrar office",
        "dean",
        "deans",
        "controller of examinations",
        "examination controller",
        "coe office",
        "finance officer",
        "finance department",
        "accounts department",
        "accounts section",
        "administrative office",
        "administration",
        "administrative staff",
        "university administration",
        "who is the vice chancellor",
        "who is the registrar",
        "who is the dean",
        "list of authorities",
        "list of offices",
        "who to contact for",
        "whom should i contact",
        "who do i contact",
        "who can help me with",
        "office contact",
        "department contact",
        "staff contact",
        "faculty contact",
        "academic advisor",
        "student advisor",
        "counsellor",
        "counselor",
        "guidance officer",
        "placement officer",
        "placement cell",
        "training and placement",
        "tnp cell",
        "research directorate",
        "research department",
        "research cell",
        "iqac",
        "internal quality assurance cell",
        "anti ragging committee",
        "anti ragging cell",
        "anti ragging squad",
        "equal opportunity cell",
        "sc st cell",
        "minority cell",
        "women cell",
        "grievance committee",
        "discipline committee",
        "library committee",
        "sports committee",
        "cultural committee",
        "examination committee",
        "academic council",
        "board of studies",
        "it cell",
        "it department",
        "computer centre",
        "computer center",
        "web development cell",
        "public relations officer",
        "pro",
        "information officer",
        "rti officer",
        "right to information",
        "rti",
    ],

    # =========================================================================
    # Contact Information — general university contact
    # =========================================================================
    "contact": [
        "contact",
        "contact information",
        "contact details",
        "contact info",
        "how to contact",
        "how can i contact",
        "how do i contact",
        "university contact",
        "university phone number",
        "university phone",
        "university email",
        "university email id",
        "university address",
        "what is the address",
        "what is the phone number",
        "what is the email",
        "phone number",
        "email address",
        "email id",
        "postal address",
        "office address",
        "campus address",
        "main campus address",
        "university website",
        "website url",
        "website link",
        "official website",
        "web address",
        "www",
        "university helpline",
        "helpline number",
        "helpline",
        "toll free number",
        "toll free",
        "emergency contact",
        "emergency number",
        "how to reach the university",
        "how to reach campus",
        "how to get to the university",
        "location map",
        "google maps location",
        "directions to university",
        "campus location",
        "where is the university located",
        "where is the campus",
        "communication address",
        "contact us",
        "reach us",
        "get in touch",
        "customer support",
        "support team",
        "university contact details",
        "phone directory",
        "telephone directory",
        "contact directory",
        "anti ragging helpline",
        "anti-ragging helpline",
        "women helpline",
        "women's helpline",
    ],

    # =========================================================================
    # Colleges — constituent colleges of the university
    # =========================================================================
    "colleges": [
        "colleges",
        "college",
        "constituent colleges",
        "affiliated colleges",
        "list of colleges",
        "college list",
        "what colleges are there",
        "what are the constituent colleges",
        "how many colleges are there",
        "colleges under the university",
        "colleges affiliated to the university",
        "colleges of the university",
        "college details",
        "college information",
        "about colleges",
        "tell me about colleges",
        "college details",
        "college info",
        "all colleges",
        "college directory",
        "college profiles",
        "college name list",
        "government colleges",
        "colleges in srinagar",
        "colleges in jammu",
        "colleges in kashmir",
        "college locations",
        "where are the colleges located",
        "college campus",
        "college addresses",
        "which colleges are part of the university",
        "list all colleges",
        "show me colleges",
        "college list",
        "colleges under cluster university",
        "cluster university colleges",
        "women colleges",
        "boys colleges",
        "co education colleges",
        "co-education colleges",
        "science colleges",
        "arts colleges",
        "commerce colleges",
        "college wise information",
        "college wise details",
        "college selection",
        "which college is best",
        "how to choose a college",
        "college comparison",
        "college courses offered",
        "college programmes",
        "college admission",
    ],

    # =========================================================================
    # Helpdesk — help, support, assistance
    # =========================================================================
    "helpdesk": [
        "help",
        "help desk",
        "helpdesk",
        "support",
        "assistance",
        "i need help",
        "can you help me",
        "can you assist me",
        "i need assistance",
        "please help",
        "help me",
        "help me please",
        "i require help",
        "i require assistance",
        "i need support",
        "help support",
        "technical support",
        "technical help",
        "it support",
        "it help",
        "system help",
        "portal help",
        "website help",
        "website support",
        "login help",
        "login support",
        "login problem",
        "login issue",
        "cannot login",
        "unable to login",
        "cant login",
        "can't login",
        "forgot my password",
        "lost password",
        "password issue",
        "password problem",
        "account help",
        "account issue",
        "account problem",
        "i am facing an issue",
        "i am having a problem",
        "i have an issue",
        "i have a problem",
        "something is not working",
        "error",
        "error message",
        "getting error",
        "bug",
        "glitch",
        "not working",
        "not responding",
        "having trouble",
        "i am stuck",
        "can you guide me",
        "guide me",
        "walk me through",
        "step by step",
        "how does this work",
        "how do i use this",
        "i dont understand",
        "i don't understand",
        "i am confused",
        "can you explain",
        "explain to me",
        "what should i do",
        "what do i do now",
        "i need guidance",
        "need help navigating",
        "troubleshoot",
        "troubleshooting",
        "fix this",
        "resolve issue",
        "resolve problem",
    ],

    # =========================================================================
    # General Information — about the university
    # =========================================================================
}

# Canonical intents that map to existing navigation categories
# These intents have a corresponding get_broad_response() handler
NAV_CATEGORY_INTENTS = {
    "admissions",
    "courses",
    "fee",
    "results",
    "datesheet",
    "scholarships",
    "examination",
    "colleges",
    "contact",
}

# Intents that exist in the navigation tree as programme levels
LEVEL_INTENTS = {"ug", "pg", "phd", "integrated", "dyd"}

# Combined set of all canonical intents
ALL_INTENTS = set(INTENT_PARAPHRASES.keys())
