"""initial baseline schema

Revision ID: 05c97c9296aa
Revises: 
Create Date: 2026-09-14 17:48:20.504854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import _UUID

# revision identifiers, used by Alembic.
revision: str = '05c97c9296aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_schemes',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aggregated_metrics',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('unique_sessions', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('avg_conversation_length', sa.Float(), nullable=True),
    sa.Column('avg_planner_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_rag_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_llm_latency_ms', sa.Float(), nullable=True),
    sa.Column('cache_hit_ratio', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('clarification_rate', sa.Float(), nullable=True),
    sa.Column('service_usage', sa.JSON(), nullable=True),
    sa.Column('programme_mentions', sa.JSON(), nullable=True),
    sa.Column('college_mentions', sa.JSON(), nullable=True),
    sa.Column('topic_mentions', sa.JSON(), nullable=True),
    sa.Column('response_source_counts', sa.JSON(), nullable=True),
    sa.Column('query_correction_count', sa.Integer(), nullable=True),
    sa.Column('p50_response_time_ms', sa.Float(), nullable=True),
    sa.Column('p90_response_time_ms', sa.Float(), nullable=True),
    sa.Column('p99_response_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agg_period_start', 'aggregated_metrics', ['period', 'period_start'], unique=False)
    op.create_index(op.f('ix_aggregated_metrics_period'), 'aggregated_metrics', ['period'], unique=False)
    op.create_index(op.f('ix_aggregated_metrics_period_start'), 'aggregated_metrics', ['period_start'], unique=False)
    op.create_table('analytics_sessions',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('anon_session_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_ids', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('abandoned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_sessions_anon_session_id'), 'analytics_sessions', ['anon_session_id'], unique=True)
    op.create_table('crawl_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('pages_found', sa.Integer(), nullable=False),
    sa.Column('new_pages', sa.Integer(), nullable=False),
    sa.Column('updated_pages', sa.Integer(), nullable=False),
    sa.Column('unchanged_pages', sa.Integer(), nullable=False),
    sa.Column('archived_pages', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('failed_pages', sa.Integer(), nullable=False),
    sa.Column('indexed_pages', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    op.create_table('exam_sessions',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('programme', sa.String(length=50), nullable=False),
    sa.Column('batch', sa.String(length=30), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('application_open_at', sa.DateTime(), nullable=True),
    sa.Column('last_date_normal', sa.DateTime(), nullable=True),
    sa.Column('last_date_late', sa.DateTime(), nullable=True),
    sa.Column('base_fee', sa.Integer(), nullable=True),
    sa.Column('late_fee', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('form_seq', sa.Integer(), nullable=True),
    sa.Column('created_by', _UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sessions_code'), 'exam_sessions', ['code'], unique=True)
    op.create_table('grievance_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_categories_name'), 'grievance_categories', ['name'], unique=True)
    op.create_index(op.f('ix_grievance_categories_slug'), 'grievance_categories', ['slug'], unique=True)
    op.create_table('interaction_events',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anon_session_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('planner_action', sa.String(length=40), nullable=True),
    sa.Column('detected_intent', sa.String(length=40), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detected_programme', sa.String(length=40), nullable=True),
    sa.Column('detected_college', sa.String(length=40), nullable=True),
    sa.Column('detected_topic', sa.String(length=60), nullable=True),
    sa.Column('detected_level', sa.String(length=20), nullable=True),
    sa.Column('detected_service', sa.String(length=40), nullable=True),
    sa.Column('response_source', sa.String(length=40), nullable=True),
    sa.Column('route_chosen', sa.String(length=40), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('planner_latency_ms', sa.Integer(), nullable=True),
    sa.Column('rag_latency_ms', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('clarification_count', sa.Integer(), nullable=True),
    sa.Column('conversation_completed', sa.Boolean(), nullable=True),
    sa.Column('conversation_abandoned', sa.Boolean(), nullable=True),
    sa.Column('service_requested', sa.String(length=40), nullable=True),
    sa.Column('knowledge_sync_used', sa.Boolean(), nullable=True),
    sa.Column('rag_used', sa.Boolean(), nullable=True),
    sa.Column('structured_lookup_used', sa.Boolean(), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=True),
    sa.Column('query_corrected', sa.Boolean(), nullable=True),
    sa.Column('query_original', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_events_anon_session_id'), 'interaction_events', ['anon_session_id'], unique=False)
    op.create_index(op.f('ix_interaction_events_conversation_id'), 'interaction_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_interaction_events_timestamp'), 'interaction_events', ['timestamp'], unique=False)
    op.create_index('ix_interaction_source', 'interaction_events', ['response_source'], unique=False)
    op.create_index('ix_interaction_ts_programme', 'interaction_events', ['timestamp', 'detected_programme'], unique=False)
    op.create_index('ix_interaction_ts_service', 'interaction_events', ['timestamp', 'detected_service'], unique=False)
    op.create_index('ix_interaction_ts_topic', 'interaction_events', ['timestamp', 'detected_topic'], unique=False)
    op.create_table('knowledge_gaps',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gap_type', sa.String(length=40), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_text', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kg_type_freq', 'knowledge_gaps', ['gap_type', 'frequency'], unique=False)
    op.create_index(op.f('ix_knowledge_gaps_gap_type'), 'knowledge_gaps', ['gap_type'], unique=False)
    op.create_table('performance_samples',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('anon_session_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_samples_stage'), 'performance_samples', ['stage'], unique=False)
    op.create_index(op.f('ix_performance_samples_timestamp'), 'performance_samples', ['timestamp'], unique=False)
    op.create_table('programme_categories',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('level_label', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('students',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('roll_no', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('programme', sa.String(length=50), nullable=False),
    sa.Column('academic_scheme', sa.String(length=20), nullable=True),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_reg_no'), 'students', ['reg_no'], unique=True)
    op.create_table('sync_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_sources_status'), 'sync_sources', ['status'], unique=False)
    op.create_index(op.f('ix_sync_sources_url'), 'sync_sources', ['url'], unique=False)
    op.create_table('website_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('normalized_title', sa.String(length=400), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_path', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('title_hash', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('doc_type', sa.String(length=20), nullable=True),
    sa.Column('classification_status', sa.String(length=30), nullable=False),
    sa.Column('classification_confidence', sa.JSON(), nullable=True),
    sa.Column('classification_signals', sa.JSON(), nullable=True),
    sa.Column('doc_meta', sa.JSON(), nullable=True),
    sa.Column('raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('raw_size', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_pages_category'), 'website_pages', ['category'], unique=False)
    op.create_index(op.f('ix_website_pages_classification_status'), 'website_pages', ['classification_status'], unique=False)
    op.create_index(op.f('ix_website_pages_content_hash'), 'website_pages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_website_pages_doc_type'), 'website_pages', ['doc_type'], unique=False)
    op.create_index(op.f('ix_website_pages_raw_sha256'), 'website_pages', ['raw_sha256'], unique=False)
    op.create_index(op.f('ix_website_pages_status'), 'website_pages', ['status'], unique=False)
    op.create_index('ix_website_pages_url', 'website_pages', ['url'], unique=False)
    op.create_table('authorities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('authority_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('office_location', sa.String(length=500), nullable=True),
    sa.Column('office_timings', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('services_offered', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('office_image', sa.String(length=500), nullable=True),
    sa.Column('working_days', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True),
    sa.Column('additional_contacts', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('source_kind', sa.String(length=20), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['grievance_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorities_category_id'), 'authorities', ['category_id'], unique=False)
    op.create_index(op.f('ix_authorities_deleted_at'), 'authorities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_authorities_department_name'), 'authorities', ['department_name'], unique=False)
    op.create_table('course_registrations',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('elective_subjects', sa.Text(), nullable=True),
    sa.Column('registered_subjects', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_registrations_student_id'), 'course_registrations', ['student_id'], unique=False)
    op.create_table('fee_receipts',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('fee_heads', sa.Text(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('pending_amount', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.String(length=20), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_receipts_student_id'), 'fee_receipts', ['student_id'], unique=False)
    op.create_table('helpdesk_tickets',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_officer', sa.String(length=200), nullable=True),
    sa.Column('assigned_department', sa.String(length=200), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_date', sa.String(length=20), nullable=True),
    sa.Column('resolved_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpdesk_tickets_student_id'), 'helpdesk_tickets', ['student_id'], unique=False)
    op.create_table('migration_certificates',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('certificate_no', sa.String(length=50), nullable=True),
    sa.Column('issue_status', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.String(length=20), nullable=True),
    sa.Column('application_date', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_certificates_student_id'), 'migration_certificates', ['student_id'], unique=False)
    op.create_table('programmes',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('category_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('degree_level', sa.String(length=40), nullable=True),
    sa.Column('scheme_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('academic_scheme', sa.String(length=20), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('fee_structure', sa.JSON(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('major_disciplines', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['programme_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheme_id'], ['academic_schemes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_programmes_category_id'), 'programmes', ['category_id'], unique=False)
    op.create_index(op.f('ix_programmes_scheme_id'), 'programmes', ['scheme_id'], unique=False)
    op.create_table('student_admit_cards',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('exam_session', sa.String(length=100), nullable=True),
    sa.Column('centre_name', sa.String(length=200), nullable=True),
    sa.Column('centre_address', sa.Text(), nullable=True),
    sa.Column('centre_code', sa.String(length=20), nullable=True),
    sa.Column('reporting_time', sa.String(length=50), nullable=True),
    sa.Column('subjects', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_admit_cards_student_id'), 'student_admit_cards', ['student_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('total_classes', sa.Integer(), nullable=True),
    sa.Column('attended_classes', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.String(length=10), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_attendance_student_id'), 'student_attendance', ['student_id'], unique=False)
    op.create_table('student_backlogs',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('improvement_applied', sa.Boolean(), nullable=True),
    sa.Column('cleared_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_backlogs_student_id'), 'student_backlogs', ['student_id'], unique=False)
    op.create_table('student_exam_forms',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('form_status', sa.String(length=50), nullable=True),
    sa.Column('subjects', sa.Text(), nullable=True),
    sa.Column('fee_status', sa.String(length=50), nullable=True),
    sa.Column('fee_amount', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('submission_date', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('exam_session_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('form_no', sa.String(length=30), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('eligibility_snapshot', sa.Text(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_exam_forms_exam_session_id'), 'student_exam_forms', ['exam_session_id'], unique=False)
    op.create_index(op.f('ix_student_exam_forms_form_no'), 'student_exam_forms', ['form_no'], unique=False)
    op.create_index(op.f('ix_student_exam_forms_student_id'), 'student_exam_forms', ['student_id'], unique=False)
    op.create_table('student_results',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('exam_roll_no', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('internal_marks', sa.Integer(), nullable=True),
    sa.Column('external_marks', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('sgpa', sa.String(length=5), nullable=True),
    sa.Column('cgpa', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_results_student_id'), 'student_results', ['student_id'], unique=False)
    op.create_table('student_revaluations',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('application_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('fee_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_revaluations_student_id'), 'student_revaluations', ['student_id'], unique=False)
    op.create_table('student_sessions',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_sessions_student_id'), 'student_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_sessions_token'), 'student_sessions', ['token'], unique=True)
    op.create_table('student_transcripts',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('credits_earned', sa.Integer(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('sgpa', sa.String(length=5), nullable=True),
    sa.Column('cgpa', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_transcripts_student_id'), 'student_transcripts', ['student_id'], unique=False)
    op.create_table('website_page_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_path', sa.String(length=500), nullable=True),
    sa.Column('raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['website_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_web_page_ver_page', 'website_page_versions', ['page_id'], unique=False)
    op.create_table('xerox_requests',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('paper_name', sa.String(length=200), nullable=True),
    sa.Column('application_date', sa.String(length=20), nullable=True),
    sa.Column('fee_status', sa.String(length=20), nullable=True),
    sa.Column('request_status', sa.String(length=50), nullable=True),
    sa.Column('estimated_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xerox_requests_student_id'), 'xerox_requests', ['student_id'], unique=False)
    op.create_table('exam_application_subjects',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('form_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['student_exam_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_application_subjects_form_id'), 'exam_application_subjects', ['form_id'], unique=False)
    op.create_table('exam_eligibility',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('form_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['student_exam_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_eligibility_form_id'), 'exam_eligibility', ['form_id'], unique=False)
    op.create_index(op.f('ix_exam_eligibility_session_id'), 'exam_eligibility', ['session_id'], unique=False)
    op.create_table('exam_payments',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('form_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('head', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('recorded_by', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['student_exam_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_payments_form_id'), 'exam_payments', ['form_id'], unique=False)
    op.create_index(op.f('ix_exam_payments_session_id'), 'exam_payments', ['session_id'], unique=False)
    op.create_table('learning_outcomes',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('programme_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('outcome_text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcomes_programme_id'), 'learning_outcomes', ['programme_id'], unique=False)
    op.create_table('minor_disciplines',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('programme_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minor_disciplines_programme_id'), 'minor_disciplines', ['programme_id'], unique=False)
    op.create_table('users',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authority_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authority_id'), 'users', ['authority_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('actor_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target', sa.String(length=400), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('original_filename', sa.String(length=400), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('academic_scheme', sa.String(length=20), nullable=True),
    sa.Column('programme', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=10), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('college_id', sa.String(length=64), nullable=True),
    sa.Column('college_name', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_college_id'), 'documents', ['college_id'], unique=False)
    op.create_index(op.f('ix_documents_scope'), 'documents', ['scope'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('grievances',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('reference', sa.String(length=36), nullable=True),
    sa.Column('authority_id', sa.String(length=36), nullable=True),
    sa.Column('student_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('student_name', sa.String(length=200), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('student_email', sa.String(length=200), nullable=True),
    sa.Column('programme', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('email_status', sa.String(length=20), nullable=True),
    sa.Column('authority_email_status', sa.String(length=20), nullable=True),
    sa.Column('tracking_token_hash', sa.String(length=128), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('original_student_input', sa.Text(), nullable=True),
    sa.Column('generated_formal_grievance', sa.Text(), nullable=True),
    sa.Column('final_grievance_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_by', sa.String(length=200), nullable=True),
    sa.Column('authority_response', sa.Text(), nullable=True),
    sa.Column('authority_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_email_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_authority_id'), 'grievances', ['authority_id'], unique=False)
    op.create_index(op.f('ix_grievances_client_request_id'), 'grievances', ['client_request_id'], unique=True)
    op.create_index(op.f('ix_grievances_created_at'), 'grievances', ['created_at'], unique=False)
    op.create_index(op.f('ix_grievances_reference'), 'grievances', ['reference'], unique=True)
    op.create_index(op.f('ix_grievances_roll_number'), 'grievances', ['roll_number'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_index(op.f('ix_grievances_student_email'), 'grievances', ['student_email'], unique=False)
    op.create_index(op.f('ix_grievances_student_id'), 'grievances', ['student_id'], unique=False)
    op.create_index(op.f('ix_grievances_tracking_token_hash'), 'grievances', ['tracking_token_hash'], unique=True)
    op.create_index(op.f('ix_grievances_user_id'), 'grievances', ['user_id'], unique=False)
    # Composite read-path index created only by the legacy _upgrade_schema()
    # bootstrap on SQLite; it is part of the logical production schema and is
    # therefore folded into the Alembic baseline.
    op.create_index('ix_grievances_authority_read', 'grievances', ['authority_id', 'is_read'], unique=False)
    op.create_table('programme_subjects',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('programme_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('minor_discipline_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['minor_discipline_id'], ['minor_disciplines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'minor_discipline_id', 'category', 'semester', 'subject_name', name='uq_programme_subject')
    )
    op.create_index(op.f('ix_programme_subjects_minor_discipline_id'), 'programme_subjects', ['minor_discipline_id'], unique=False)
    op.create_index(op.f('ix_programme_subjects_programme_id'), 'programme_subjects', ['programme_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('university_notices',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('notice_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('original_filename', sa.String(length=400), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=600), nullable=False),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('programme_ids', sa.Text(), nullable=True),
    sa.Column('exam_type', sa.String(length=60), nullable=True),
    sa.Column('exam_session_label', sa.String(length=120), nullable=True),
    sa.Column('notification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('validation_flags', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('created_by', _UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_notices_extraction_status'), 'university_notices', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_university_notices_notice_type'), 'university_notices', ['notice_type'], unique=False)
    op.create_index(op.f('ix_university_notices_sha256'), 'university_notices', ['sha256'], unique=False)
    op.create_table('curriculum_documents',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('programme_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('document_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_documents_document_id'), 'curriculum_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_curriculum_documents_programme_id'), 'curriculum_documents', ['programme_id'], unique=False)
    op.create_table('curriculum_uploads',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('programme_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('scheme_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('document_id', _UUID(as_uuid=True), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=40), nullable=True),
    sa.Column('academic_session', sa.String(length=40), nullable=True),
    sa.Column('programme_name', sa.String(length=150), nullable=True),
    sa.Column('programme_code', sa.String(length=40), nullable=True),
    sa.Column('scheme_name', sa.String(length=100), nullable=True),
    sa.Column('scheme_code', sa.String(length=40), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', _UUID(as_uuid=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheme_id'], ['academic_schemes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_uploads_document_id'), 'curriculum_uploads', ['document_id'], unique=False)
    op.create_index(op.f('ix_curriculum_uploads_programme_code'), 'curriculum_uploads', ['programme_code'], unique=False)
    op.create_index(op.f('ix_curriculum_uploads_programme_id'), 'curriculum_uploads', ['programme_id'], unique=False)
    op.create_index(op.f('ix_curriculum_uploads_scheme_id'), 'curriculum_uploads', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_curriculum_uploads_sha256'), 'curriculum_uploads', ['sha256'], unique=False)
    op.create_index(op.f('ix_curriculum_uploads_status'), 'curriculum_uploads', ['status'], unique=False)
    op.create_table('date_sheet_entries',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('notice_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.String(length=20), nullable=True),
    sa.Column('programme_name', sa.String(length=200), nullable=True),
    sa.Column('stream', sa.String(length=60), nullable=True),
    sa.Column('semester', sa.String(length=10), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('exam_type', sa.String(length=60), nullable=True),
    sa.Column('exam_date', sa.String(length=10), nullable=True),
    sa.Column('day', sa.String(length=12), nullable=True),
    sa.Column('start_time', sa.String(length=8), nullable=True),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('paper_code', sa.String(length=30), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(length=200), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('validation_flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['university_notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_sheet_entries_extraction_status'), 'date_sheet_entries', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_date_sheet_entries_notice_id'), 'date_sheet_entries', ['notice_id'], unique=False)
    op.create_index(op.f('ix_date_sheet_entries_programme_id'), 'date_sheet_entries', ['programme_id'], unique=False)
    op.create_index(op.f('ix_date_sheet_entries_semester'), 'date_sheet_entries', ['semester'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('document_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_doc_chunk')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('grievance_attachments',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('grievance_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_attachments_grievance_id'), 'grievance_attachments', ['grievance_id'], unique=False)
    op.create_table('grievance_notifications',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('grievance_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('recipient_role', sa.String(length=20), nullable=False),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grievance_id', 'event_type', 'recipient_role', name='uq_grievance_notification_event')
    )
    op.create_index(op.f('ix_grievance_notifications_created_at'), 'grievance_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_grievance_notifications_grievance_id'), 'grievance_notifications', ['grievance_id'], unique=False)
    op.create_table('grievance_status_history',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('grievance_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_by_role', sa.String(length=30), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_status_history_created_at'), 'grievance_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_grievance_status_history_grievance_id'), 'grievance_status_history', ['grievance_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', _UUID(as_uuid=True), nullable=False),
    sa.Column('conversation_id', _UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_grievance_status_history_grievance_id'), table_name='grievance_status_history')
    op.drop_index(op.f('ix_grievance_status_history_created_at'), table_name='grievance_status_history')
    op.drop_table('grievance_status_history')
    op.drop_index(op.f('ix_grievance_notifications_grievance_id'), table_name='grievance_notifications')
    op.drop_index(op.f('ix_grievance_notifications_created_at'), table_name='grievance_notifications')
    op.drop_table('grievance_notifications')
    op.drop_index(op.f('ix_grievance_attachments_grievance_id'), table_name='grievance_attachments')
    op.drop_table('grievance_attachments')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_date_sheet_entries_semester'), table_name='date_sheet_entries')
    op.drop_index(op.f('ix_date_sheet_entries_programme_id'), table_name='date_sheet_entries')
    op.drop_index(op.f('ix_date_sheet_entries_notice_id'), table_name='date_sheet_entries')
    op.drop_index(op.f('ix_date_sheet_entries_extraction_status'), table_name='date_sheet_entries')
    op.drop_table('date_sheet_entries')
    op.drop_index(op.f('ix_curriculum_uploads_status'), table_name='curriculum_uploads')
    op.drop_index(op.f('ix_curriculum_uploads_sha256'), table_name='curriculum_uploads')
    op.drop_index(op.f('ix_curriculum_uploads_scheme_id'), table_name='curriculum_uploads')
    op.drop_index(op.f('ix_curriculum_uploads_programme_id'), table_name='curriculum_uploads')
    op.drop_index(op.f('ix_curriculum_uploads_programme_code'), table_name='curriculum_uploads')
    op.drop_index(op.f('ix_curriculum_uploads_document_id'), table_name='curriculum_uploads')
    op.drop_table('curriculum_uploads')
    op.drop_index(op.f('ix_curriculum_documents_programme_id'), table_name='curriculum_documents')
    op.drop_index(op.f('ix_curriculum_documents_document_id'), table_name='curriculum_documents')
    op.drop_table('curriculum_documents')
    op.drop_index(op.f('ix_university_notices_sha256'), table_name='university_notices')
    op.drop_index(op.f('ix_university_notices_notice_type'), table_name='university_notices')
    op.drop_index(op.f('ix_university_notices_extraction_status'), table_name='university_notices')
    op.drop_table('university_notices')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_programme_subjects_programme_id'), table_name='programme_subjects')
    op.drop_index(op.f('ix_programme_subjects_minor_discipline_id'), table_name='programme_subjects')
    op.drop_table('programme_subjects')
    op.drop_index(op.f('ix_grievances_user_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_tracking_token_hash'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_student_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_student_email'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_roll_number'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_reference'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_created_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_client_request_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_authority_id'), table_name='grievances')
    op.drop_index('ix_grievances_authority_read', table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_scope'), table_name='documents')
    op.drop_index(op.f('ix_documents_college_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_authority_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_minor_disciplines_programme_id'), table_name='minor_disciplines')
    op.drop_table('minor_disciplines')
    op.drop_index(op.f('ix_learning_outcomes_programme_id'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.drop_index(op.f('ix_exam_payments_session_id'), table_name='exam_payments')
    op.drop_index(op.f('ix_exam_payments_form_id'), table_name='exam_payments')
    op.drop_table('exam_payments')
    op.drop_index(op.f('ix_exam_eligibility_session_id'), table_name='exam_eligibility')
    op.drop_index(op.f('ix_exam_eligibility_form_id'), table_name='exam_eligibility')
    op.drop_table('exam_eligibility')
    op.drop_index(op.f('ix_exam_application_subjects_form_id'), table_name='exam_application_subjects')
    op.drop_table('exam_application_subjects')
    op.drop_index(op.f('ix_xerox_requests_student_id'), table_name='xerox_requests')
    op.drop_table('xerox_requests')
    op.drop_index('ix_web_page_ver_page', table_name='website_page_versions')
    op.drop_table('website_page_versions')
    op.drop_index(op.f('ix_student_transcripts_student_id'), table_name='student_transcripts')
    op.drop_table('student_transcripts')
    op.drop_index(op.f('ix_student_sessions_token'), table_name='student_sessions')
    op.drop_index(op.f('ix_student_sessions_student_id'), table_name='student_sessions')
    op.drop_table('student_sessions')
    op.drop_index(op.f('ix_student_revaluations_student_id'), table_name='student_revaluations')
    op.drop_table('student_revaluations')
    op.drop_index(op.f('ix_student_results_student_id'), table_name='student_results')
    op.drop_table('student_results')
    op.drop_index(op.f('ix_student_exam_forms_student_id'), table_name='student_exam_forms')
    op.drop_index(op.f('ix_student_exam_forms_form_no'), table_name='student_exam_forms')
    op.drop_index(op.f('ix_student_exam_forms_exam_session_id'), table_name='student_exam_forms')
    op.drop_table('student_exam_forms')
    op.drop_index(op.f('ix_student_backlogs_student_id'), table_name='student_backlogs')
    op.drop_table('student_backlogs')
    op.drop_index(op.f('ix_student_attendance_student_id'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_student_admit_cards_student_id'), table_name='student_admit_cards')
    op.drop_table('student_admit_cards')
    op.drop_index(op.f('ix_programmes_scheme_id'), table_name='programmes')
    op.drop_index(op.f('ix_programmes_category_id'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_migration_certificates_student_id'), table_name='migration_certificates')
    op.drop_table('migration_certificates')
    op.drop_index(op.f('ix_helpdesk_tickets_student_id'), table_name='helpdesk_tickets')
    op.drop_table('helpdesk_tickets')
    op.drop_index(op.f('ix_fee_receipts_student_id'), table_name='fee_receipts')
    op.drop_table('fee_receipts')
    op.drop_index(op.f('ix_course_registrations_student_id'), table_name='course_registrations')
    op.drop_table('course_registrations')
    op.drop_index(op.f('ix_authorities_department_name'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_deleted_at'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_category_id'), table_name='authorities')
    op.drop_table('authorities')
    op.drop_index('ix_website_pages_url', table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_status'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_raw_sha256'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_doc_type'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_content_hash'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_classification_status'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_category'), table_name='website_pages')
    op.drop_table('website_pages')
    op.drop_index(op.f('ix_sync_sources_url'), table_name='sync_sources')
    op.drop_index(op.f('ix_sync_sources_status'), table_name='sync_sources')
    op.drop_table('sync_sources')
    op.drop_index(op.f('ix_students_reg_no'), table_name='students')
    op.drop_table('students')
    op.drop_table('programme_categories')
    op.drop_index(op.f('ix_performance_samples_timestamp'), table_name='performance_samples')
    op.drop_index(op.f('ix_performance_samples_stage'), table_name='performance_samples')
    op.drop_table('performance_samples')
    op.drop_index(op.f('ix_knowledge_gaps_gap_type'), table_name='knowledge_gaps')
    op.drop_index('ix_kg_type_freq', table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    op.drop_index('ix_interaction_ts_topic', table_name='interaction_events')
    op.drop_index('ix_interaction_ts_service', table_name='interaction_events')
    op.drop_index('ix_interaction_ts_programme', table_name='interaction_events')
    op.drop_index('ix_interaction_source', table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_timestamp'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_conversation_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_anon_session_id'), table_name='interaction_events')
    op.drop_table('interaction_events')
    op.drop_index(op.f('ix_grievance_categories_slug'), table_name='grievance_categories')
    op.drop_index(op.f('ix_grievance_categories_name'), table_name='grievance_categories')
    op.drop_table('grievance_categories')
    op.drop_index(op.f('ix_exam_sessions_code'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_analytics_sessions_anon_session_id'), table_name='analytics_sessions')
    op.drop_table('analytics_sessions')
    op.drop_index(op.f('ix_aggregated_metrics_period_start'), table_name='aggregated_metrics')
    op.drop_index(op.f('ix_aggregated_metrics_period'), table_name='aggregated_metrics')
    op.drop_index('ix_agg_period_start', table_name='aggregated_metrics')
    op.drop_table('aggregated_metrics')
    op.drop_table('academic_schemes')
    # ### end Alembic commands ###
